aws/jsii-rosetta

src/languages/go.ts, src/translate.ts, test/translations/expressions/property_access.cs, test/translations/expressions/property_access.go, test/translations/expressions/property_access.java, test/translations/expressions/property_access.py, test/translations/expressions/property_access.ts
Go caches translated names for identifiers on the value symbol, however TypeScript since 3.9 changed how indexed property accesses are represented and uses a single symbol for all accesses through an index signature, causing the cache to incorrectly map all indexed accesses to the name of the very first one.
Fixes this issue by not using the symbol as a cache key when it corresponds to a transient signature.
---
=> fix(go): indexed property access incorrectly renamed

package.json, yarn.lock
`commonmark` was mistakenly declared as `*`, which is too broad and risks cuasing runtime issues, and `@jsii/check-node` was using a caret dependency, which would lead to mis-representing what versions a release had been tested against.
---
=> chore: fixup dependencies on `commonmark` and `@jsii/check-node`

SUPPORT.md
Since we did not release 4.9.x.
---
=> chore: support policy to mention 5.0.x instead of 4.9.x

src/json.ts, src/tablets/tablets.ts
It appears the trim-cache test using tablet compression occasionally fails in CI/CD. I suspect this is due to the `save` function returning before the GZip stream has bene closed, resulting in the subsequent read attempting to consume an incomplete GZip object.
This adds the necessary provisions to ensure the GZip stream is closed (or failed) before `save` returns.
Forward-ported from aws/jsii#4043
---
=> fix: flakey trim-cache test

package.json, src/commands/extract.ts, src/jsii/assemblies.ts, src/main.ts, src/rosetta-translator.ts, src/snippet-dependencies.ts, src/snippet.ts, src/translate.ts, test/commands/extract.test.ts, test/commands/trim-cache.test.ts, test/jsii/assemblies.test.ts, test/testutil.ts, yarn.lock
Rosetta has a feature to include external packages into its example compilation dependency tree, so that you can write examples in your README using packages that depend on the package you're writing the README for. You couldn't have those dependencies in your actual dependency tree, but there is a special section in `package.json` that can do it.
Schematically:
```
mydep                          
▲                            
│                            
mypackage   < write a compilable example that uses 'myinteg'
▲ 
│                            
myinteg                          
```
Put the following into `package.json`:
```json
{
"jsiiRosetta": {
"exampleDependencies": {
"myinteg": "^1.2.3"
}
}
}
```
While this feature was advertised, it didn't actually work:
* The dependency closure …
=> fix: exampleDependencies aren't used

src/snippet-dependencies.ts
=> fix: allow prereleases for `*`

src/index.ts, src/main.ts
This function is already used in other tools and should be available as programmatic API.
Both `--loose` and `--language` were using the `-l` alias, causing the language option to be booleans instead of strings.
---
=> fix: export transliterateAssembly and fix bug with transliterate cli

.github/workflows/auto-tag-dev-v5.0.yml, .github/workflows/auto-tag-dev.yml, .github/workflows/auto-tag-releases-v5.0.yml, .github/workflows/auto-tag-releases.yml, .github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/upgrade-main.yml, .github/workflows/upgrade-maintenance-v5.0.yml, .projen/deps.json, .projenrc.ts, package.json, yarn.lock
The  upgrade-maintenance-v5.0 workflow is failing with the message:
```
error get-stream@7.0.0: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.18.0"
```
---
=> chore: update minNodeVersion to 16

.github/workflows/upgrade-maintenance-v5.0.yml, projenrc/upgrade-dependencies.ts
Set `CI=false` in the back-porting environment so that `yarn projen` runs the `install` task instead of the `install:ci` task (which prevents lockfile updates).
---
=> chore: upgrade workflow fails on install:ci

.projen/deps.json, .projenrc.ts, package.json, src/jsii/jsii-utils.ts, tsconfig.dev.json, tsconfig.json, yarn.lock
Using the `common` submodule directly avoids bundling all of jsii.
---
=> fix: import jsii submodule

.github/workflows/release.yml, projenrc/release.ts
Otherwise, the latest-dated release will be considered "the" latest, while we want this to only apply to the release that is tagged as "latest" on npm as well.
---
=> chore: set latest flag on GitHub releases explicitly

projenrc/upgrade-dependencies.ts
We do not use the `exclude` keyword and likely will not for the foreseeable future. Just dropping it for now. We will have to re-implement that if we need it but I don't see why we would -- this decision was also made in projen: https://github.com/projen/projen/pull/2845/files. This continues work started because projen had breaking changes.
---
=> chore: fix upgrade-dependencies task

src/fixtures.ts
Implementing the workaround mentioned in the linked issue. The only downside of this change is losing out on the performance improvements in v20.5.
re https://github.com/tschaub/mock-fs/issues/377
---
=> chore: mockfs broken on node v20.5+

.github/workflows/build.yml, src/translate_all.ts
According to the README, `process.env.JSII_ROSETTA_MAX_WORKER_COUNT` should override the other logic. It currently does not.
---
=> fix: JSII_ROSETTA_MAX_WORKER_COUNT is not respected when higher than 50% of cores

src/languages/target-language.ts
The signature overwrite for targetName using TargetLanguage.VISUALIZE causes and error, because the enum value is stripped from the generate type declarations. We need to also strip the signature overwrite.
I manually checked the output to confirm. Not sure how else to test this.
---
=> fix: 'TargetLanguage' has no exported member 'VISUALIZE'

.projen/tasks.json, .projenrc.ts, src/languages/target-language.ts, tsconfig.dev.json, tsconfig.json
We are using the `@internal` directive to instruct typescript compiler to drop some statements during compilation.
This may cause the compiler to emit invalid declarations if we are not careful.
To guarantee that our declarations are valid, we do an additional run of tsc on the output.
---
=> fix: error TS2339: Property 'VISUALIZE' does not exist on type 'typeof TargetLanguage'

.github/workflows/backport.yml, projenrc/pull-request-backport.ts
=> chore(ci): fix backport workflow is failing when PR is not yet merged

.backportrc.json, .github/workflows/auto-tag-dev-v5.2.yml, .github/workflows/auto-tag-dev-v5.3.yml, .github/workflows/auto-tag-dev.yml, .github/workflows/auto-tag-releases-v5.2.yml, .github/workflows/auto-tag-releases-v5.3.yml, .github/workflows/auto-tag-releases.yml, .github/workflows/upgrade-maintenance-v5.2.yml, .github/workflows/upgrade-maintenance-v5.3.yml, .projenrc.ts, projenrc/release.ts, projenrc/support.ts, projenrc/tag-release.ts, projenrc/upgrade-dependencies.ts
Same as https://github.com/aws/jsii-compiler/pull/998, but for jsii-rosetta
This repo was using an automatic backport feature for repository config. As part of daily upgrades, the projen config would be checked out from `main` and applied to maintenance branches. However because we also defined the current version in this config, this inadvertently changed the current version for maintenance branches as well! In practice that meant that the release tagging workflow tagged the wrong release lines.
This fix does two things: 
- Disable the automatic backport of configuration in favor of the new, explicit label based backport feature (see it in action on this PR!)
- Add an explicit release line option to the tagging workflow, that will be compared against the detected TypeScript version and …
=> chore: restore ability to release maintenance version lines

.github/workflows/build.yml, projenrc/build-workflow.ts
We had a PR https://github.com/aws/jsii-compiler/pull/1191 that got merged despite a failure in Node22 tests.
This happened because on a failure of one of the matrix builds, the job that is unifying them is skipped. This is documented behavior:
The fix is to make sure the combination step always runs and manually check the status of the matrix build.
---
=> chore: fix ci PRs might get merged with failing tests

src/commands/transliterate.ts, src/jsii/assemblies.ts, src/snippet.ts
The parallel execution of `withDependencies` inside `allTypeScriptSnippets` caused a large spike in access to the file system. On systems with only a low number of available file descriptors, this will cause transliteration to fail.
Downstream tools usually run transliteration once and cache the results for additional runs. For example when converting individual submodules of an assembly. When transliteration fails, caches cannot be written, which ultimately leads to extremely long and still failing execution times for these tools.
This change causes a moderate slow-down of factor 1.03 ± 0.14 compared to previous code (see benchmark). To resolve the issue, this is acceptable. During debugging I noticed a number of potential future performance improvements, including (re-)introducing …
=> fix: extracting snippets cause large spike in file system access

.github/workflows/auto-tag-dev-v5.7.yml, .github/workflows/auto-tag-dev-v5.8.yml, .github/workflows/auto-tag-dev.yml, .github/workflows/auto-tag-releases-v5.7.yml, .github/workflows/auto-tag-releases-v5.8.yml, .github/workflows/auto-tag-releases.yml, .github/workflows/build.yml, .github/workflows/release.yml, .kiro/steering/new-jsii-compiler-version.md, .projen/deps.json, .projenrc.ts, package.json, projenrc/support.ts, releases.json, yarn.lock
Update minNodeVersion following AWS CDK extended support policy.
This ensures compatibility with the latest CDK Node.js support timeline and removes support for Node.js versions that are no longer supported by CDK (including the 6-month extension period).
---
=> fix: correct Node.js minimum version
